db.oauthaccesstokens.drop()
db.createCollection("oauthclients")
db.sampleframes.createIndex( { "clientId": 1 }, { unique: true } )
db.createCollection("oauthusers")
db.sampleframes.createIndex( { "username": 1 }, { unique: true } )
db.createCollection("oauthaccesstokens")
db.createCollection("sampleframes")
//db.sampleframes.createIndex( { "id": 1 }, { unique: true } )
db.sampleframes.createIndex( { "datasetId": 1 }, { unique: false } )
db.sampleframes.remove({})
